# Generated by Django 4.1.7 on 2023-05-26 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stacionar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'ordering': ['name', 'number'], 'verbose_name': 'Відділення', 'verbose_name_plural': 'Відділення'},
        ),
        migrations.AlterModelOptions(
            name='diagnoses',
            options={'ordering': ['type_name', 'name'], 'verbose_name': 'Діагнози', 'verbose_name_plural': 'Діагнози'},
        ),
        migrations.AlterModelOptions(
            name='direction',
            options={'ordering': ['direction'], 'verbose_name': 'Направлення', 'verbose_name_plural': 'Направлення'},
        ),
        migrations.AlterModelOptions(
            name='doctors',
            options={'ordering': ['last_name', 'first_name', 'middle_name', 'specialization'], 'verbose_name': 'Лікарі', 'verbose_name_plural': 'Лікарі'},
        ),
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ['patient_paper'], 'verbose_name': 'Лист пацієнта', 'verbose_name_plural': 'Лист пацієнта'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['last_name', 'first_name', 'middle_name', 'time_create'], 'verbose_name': 'Пацієнти', 'verbose_name_plural': 'Пацієнти'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['result'], 'verbose_name': 'Результат лікування', 'verbose_name_plural': 'Результат лікування'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['status'], 'verbose_name': 'Статус пацієнта', 'verbose_name_plural': 'Статус пацієнта'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['type_patient'], 'verbose_name': 'Тип пацієнта', 'verbose_name_plural': 'Тип пацієнта'},
        ),
        migrations.AlterField(
            model_name='departments',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Назва відділення'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='number',
            field=models.IntegerField(verbose_name='Номер відділення'),
        ),
        migrations.AlterField(
            model_name='diagnoses',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Діагноз'),
        ),
        migrations.AlterField(
            model_name='diagnoses',
            name='type_name',
            field=models.CharField(max_length=255, verbose_name='Клас діагнозу'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='direction',
            field=models.CharField(max_length=50, verbose_name='Направлення'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='middle_name',
            field=models.CharField(max_length=50, null=True, verbose_name='По-батькові'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='specialization',
            field=models.CharField(max_length=255, verbose_name='Спеціалізація'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='patient_paper',
            field=models.CharField(max_length=50, verbose_name='Лист пацієнта'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stacionar.departments', verbose_name='Відділення'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stacionar.diagnoses', verbose_name='Діагноз'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stacionar.direction', verbose_name='Направлення'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='direction_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Назва закладу направлення'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stacionar.doctors', verbose_name='Лікар'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(max_length=50, null=True, verbose_name='По-батькові'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_paper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='stacionar.paper', verbose_name='Лист пацієнта'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stacionar.result', verbose_name='Результат'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='stacionar.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Зараховано'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='time_of_beginning',
            field=models.DateTimeField(null=True, verbose_name='Початок хвороби'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='time_of_ending',
            field=models.DateTimeField(null=True, verbose_name='Виписано'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дані оновлено'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='type_patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stacionar.type', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='result',
            name='result',
            field=models.CharField(max_length=50, verbose_name='Результат лікування'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=50, verbose_name='Статус пацієнта'),
        ),
        migrations.AlterField(
            model_name='type',
            name='type_patient',
            field=models.CharField(max_length=50, verbose_name='Тип пацієнта'),
        ),
    ]
